import streamlit as st
import pandas as pd
import altair as alt
from datetime import datetime
from typing import Optional
from services import github_service, openai_service
from utils import format_number, format_timestamp, get_language_color, get_logger
from config import settings

logger = get_logger(__name__)


def generate_comparison_markdown(m1, m2, ai_analysis: Optional[str] = None) -> str:
    """Generate a structured Markdown dossier comparing two developers."""
    u1, u2 = m1.user, m2.user
    s1, s2 = m1.stats, m2.stats

    lines = [
        f"# ⚔️ Developer Battle: @{u1.login} vs @{u2.login}",
        f"*Generated on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} via GitHub Stalker Pro*",
        "",
        "## 👤 Profile Overviews",
        f"| Metric | @{u1.login} | @{u2.login} |",
        "| :--- | :--- | :--- |",
        f"| **Full Name** | {u1.display_name} | {u2.display_name} |",
        f"| **Bio** | {u1.bio or 'N/A'} | {u2.bio or 'N/A'} |",
        f"| **Company** | {u1.company or 'N/A'} | {u2.company or 'N/A'} |",
        f"| **Location** | {u1.location or 'N/A'} | {u2.location or 'N/A'} |",
        f"| **Followers** | {u1.followers:,} | {u2.followers:,} |",
        f"| **Following** | {u1.following:,} | {u2.following:,} |",
        "",
        "## 📊 Head-to-Head Statistics",
        f"| Stat | @{u1.login} | @{u2.login} | Leader |",
        "| :--- | :--- | :--- | :--- |",
        f"| **Public Repositories** | {s1.total_repos} | {s2.total_repos} | {'@' + u1.login if s1.total_repos > s2.total_repos else ('@' + u2.login if s2.total_repos > s1.total_repos else 'Tie')} |",
        f"| **Total Stars Earned** | {s1.total_stars:,} | {s2.total_stars:,} | {'@' + u1.login if s1.total_stars > s2.total_stars else ('@' + u2.login if s2.total_stars > s1.total_stars else 'Tie')} |",
        f"| **Total Forks** | {s1.total_forks:,} | {s2.total_forks:,} | {'@' + u1.login if s1.total_forks > s2.total_forks else ('@' + u2.login if s2.total_forks > s1.total_forks else 'Tie')} |",
        f"| **Followers** | {u1.followers:,} | {u2.followers:,} | {'@' + u1.login if u1.followers > u2.followers else ('@' + u2.login if u2.followers > u1.followers else 'Tie')} |",
        "",
        "## 🌟 Top Repositories",
        f"### @{u1.login}",
    ]
    for r in s1.top_repos[:3]:
        lines.append(f"- **[{r.name}]({r.html_url})** ({r.language or 'Unknown'}) — ★ {r.stargazers_count:,} | ⑂ {r.forks_count:,}")
    
    lines.append(f"\n### @{u2.login}")
    for r in s2.top_repos[:3]:
        lines.append(f"- **[{r.name}]({r.html_url})** ({r.language or 'Unknown'}) — ★ {r.stargazers_count:,} | ⑂ {r.forks_count:,}")

    if ai_analysis:
        lines.extend([
            "",
            "## 🤖 AI Architectural Analysis",
            ai_analysis
        ])

    lines.extend([
        "",
        "---",
        "*Report generated by GitHub Stalker Pro using Model Context Protocol (MCP)*"
    ])
    return "\n".join(lines)

def stream_ai_comparison(m1, m2):
    """Stream AI comparison between two developers using local model proxy."""
    u1, u2 = m1.user, m2.user
    s1, s2 = m1.stats, m2.stats

    u1_repos = ", ".join([f"{r.name} (★{r.stargazers_count}, {r.language})" for r in s1.top_repos[:4]])
    u2_repos = ", ".join([f"{r.name} (★{r.stargazers_count}, {r.language})" for r in s2.top_repos[:4]])
    
    u1_langs = ", ".join([f"{l.language} ({l.percentage}%)" for l in m1.language_breakdown[:4]])
    u2_langs = ", ".join([f"{l.language} ({l.percentage}%)" for l in m2.language_breakdown[:4]])

    prompt = f"""Compare these two software developers based on their public GitHub profiles:

Developer 1: @{u1.login} ({u1.display_name})
- Bio: {u1.bio or 'N/A'}
- Primary Languages: {u1_langs}
- Key Repositories: {u1_repos}
- Total Stars: {s1.total_stars:,} | Total Repos: {s1.total_repos}

Developer 2: @{u2.login} ({u2.display_name})
- Bio: {u2.bio or 'N/A'}
- Primary Languages: {u2_langs}
- Key Repositories: {u2_repos}
- Total Stars: {s2.total_stars:,} | Total Repos: {s2.total_repos}

Please provide:
1. **Architectural & Technology Domain Comparison**: Contrast their core engineering focus, primary tech stacks, and domain (e.g. systems/kernels vs web/frameworks vs devops).
2. **Software Design Philosophy**: How their codebases approach design, simplicity vs completeness, and ecosystem influence.
3. **Open-Source Footprint & Impact**: Significance of their most notable contributions to the broader industry.
4. **Summary / Key Takeaway**: A concise 2-sentence synthesis of their complementary engineering styles.
"""

    client = openai_service.get_client()
    stream = client.chat.completions.create(
        model=settings.openai_model,
        messages=[
            {"role": "system", "content": "You are an elite software engineering architect and open-source historian. Provide detailed, factual, and articulate comparisons."},
            {"role": "user", "content": prompt}
        ],
        stream=True,
        temperature=0.3
    )

    for chunk in stream:
        if chunk.choices and chunk.choices[0].delta.content:
            yield chunk.choices[0].delta.content

def render_comparison_page():
    """Main entry point for Developer Comparison page."""
    st.markdown(
        """
        <div style="text-align:center; padding:1.5rem 0 1rem 0;">
            <h1 style="font-size:2.6rem; font-weight:800; background:linear-gradient(135deg, #58a6ff 0%, #f778ba 50%, #a371f7 100%); -webkit-background-clip:text; -webkit-text-fill-color:transparent; margin-bottom:0.5rem;">
                ⚔️ Developer Comparison Showdown
            </h1>
            <p style="color:#8b949e; font-size:1.1rem; max-width:700px; margin:0 auto 1.5rem auto;">
                Analyze and compare two GitHub developers side-by-side with head-to-head metric scorecards, comparative language breakdowns, and AI architectural synthesis.
            </p>
        </div>
        """,
        unsafe_allow_html=True
    )

    # Initialize session state for comparison targets if not present
    if "compare_user1" not in st.session_state:
        st.session_state.compare_user1 = ""
    if "compare_user2" not in st.session_state:
        st.session_state.compare_user2 = ""
    if "compare_submitted" not in st.session_state:
        st.session_state.compare_submitted = False
    if "compare_ai_analysis" not in st.session_state:
        st.session_state.compare_ai_analysis = None

    # ==========================================
    # 1. Input Form
    # ==========================================
    with st.form(key="comparison_form"):
        c_col1, c_col_vs, c_col2 = st.columns([5, 1, 5])
        
        with c_col1:
            user1_input = st.text_input(
                label="Developer 1 (GitHub Username)",
                value=st.session_state.compare_user1,
                placeholder="Enter first GitHub username"
            )
        
        with c_col_vs:
            st.markdown(
                """
                <div style="display:flex; justify-content:center; align-items:center; height:100%; padding-top:1.8rem;">
                    <span class="vs-badge">VS</span>
                </div>
                """,
                unsafe_allow_html=True
            )

        with c_col2:
            user2_input = st.text_input(
                label="Developer 2 (GitHub Username)",
                value=st.session_state.compare_user2,
                placeholder="Enter second GitHub username"
            )

        compare_clicked = st.form_submit_button("⚔️ Launch Developer Showdown", use_container_width=True)

        if compare_clicked:
            if user1_input and user2_input and user1_input.strip() and user2_input.strip():
                st.session_state.compare_user1 = user1_input.strip()
                st.session_state.compare_user2 = user2_input.strip()
                st.session_state.compare_submitted = True
                st.session_state.compare_ai_analysis = None
                st.rerun()
            else:
                st.warning("Please enter two valid GitHub usernames to compare.")

    if not st.session_state.compare_submitted:
        st.info("💡 Enter any two GitHub usernames above and click **⚔️ Launch Developer Showdown** to compare them side-by-side.")
        return

    dev1 = st.session_state.compare_user1
    dev2 = st.session_state.compare_user2

    # ==========================================
    # 3. Data Fetching
    # ==========================================
    with st.spinner(f"Analyzing GitHub profiles @{dev1} and @{dev2} via MCP tools..."):
        m1 = github_service.get_dashboard_metrics(dev1)
        m2 = github_service.get_dashboard_metrics(dev2)

    if not m1 or not m2:
        if not m1:
            st.error(f"❌ Could not retrieve profile data for **@{dev1}**. Please check if the username exists or if your GitHub PAT has hit rate limits.")
        if not m2:
            st.error(f"❌ Could not retrieve profile data for **@{dev2}**. Please check if the username exists or if your GitHub PAT has hit rate limits.")
        return

    u1, u2 = m1.user, m2.user
    s1, s2 = m1.stats, m2.stats

    st.markdown("---")

    # ==========================================
    # 4. Side-by-Side Profile Dossiers
    # ==========================================
    col_p1, col_p2 = st.columns(2)
    with col_p1:
        avatar1 = u1.avatar_url or "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"
        st.markdown(
            f"""
            <div class="profile-card" style="height:100%;">
                <img src="{avatar1}" class="profile-avatar" alt="{u1.login}"/>
                <div class="profile-name">{u1.display_name}</div>
                <div class="profile-username"><a href="https://github.com/{u1.login}" target="_blank" style="color:#58a6ff; text-decoration:none;">@{u1.login}</a></div>
                <div class="profile-bio">{u1.bio or 'No bio available.'}</div>
                <div class="profile-meta">
                    <span class="meta-item">📍 {u1.location or 'Global'}</span>
                    <span class="meta-item">🏢 {u1.company or 'Independent'}</span>
                    <span class="meta-item">👥 <b>{format_number(u1.followers)}</b> Followers</span>
                </div>
            </div>
            """,
            unsafe_allow_html=True
        )

    with col_p2:
        avatar2 = u2.avatar_url or "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"
        st.markdown(
            f"""
            <div class="profile-card" style="height:100%;">
                <img src="{avatar2}" class="profile-avatar" alt="{u2.login}"/>
                <div class="profile-name">{u2.display_name}</div>
                <div class="profile-username"><a href="https://github.com/{u2.login}" target="_blank" style="color:#f778ba; text-decoration:none;">@{u2.login}</a></div>
                <div class="profile-bio">{u2.bio or 'No bio available.'}</div>
                <div class="profile-meta">
                    <span class="meta-item">📍 {u2.location or 'Global'}</span>
                    <span class="meta-item">🏢 {u2.company or 'Independent'}</span>
                    <span class="meta-item">👥 <b>{format_number(u2.followers)}</b> Followers</span>
                </div>
            </div>
            """,
            unsafe_allow_html=True
        )

    st.markdown("<br/>", unsafe_allow_html=True)

    # ==========================================
    # 5. Head-to-Head Scorecard
    # ==========================================
    st.subheader("📊 Head-to-Head Scorecard")
    
    def render_metric_battle(label, val1, val2, num1, num2):
        lead1 = "🏆" if num1 > num2 else ""
        lead2 = "🏆" if num2 > num1 else ""
        border1 = "border:1px solid #58a6ff;" if num1 > num2 else "border:1px solid #30363d;"
        border2 = "border:1px solid #f778ba;" if num2 > num1 else "border:1px solid #30363d;"
        
        st.markdown(
            f"""
            <div style="display:flex; justify-content:space-between; align-items:center; background:#161b22; border-radius:12px; padding:0.8rem 1.2rem; margin-bottom:0.8rem; border:1px solid #30363d;">
                <div style="flex:1; text-align:left; font-size:1.1rem; font-weight:700; color:#58a6ff;">
                    {val1} <span style="font-size:0.85rem; color:#e3b341;">{lead1}</span>
                </div>
                <div style="flex:1; text-align:center; text-transform:uppercase; font-size:0.85rem; color:#8b949e; letter-spacing:1px; font-weight:600;">
                    {label}
                </div>
                <div style="flex:1; text-align:right; font-size:1.1rem; font-weight:700; color:#f778ba;">
                    <span style="font-size:0.85rem; color:#e3b341;">{lead2}</span> {val2}
                </div>
            </div>
            """,
            unsafe_allow_html=True
        )

    render_metric_battle("Total Stars Earned", f"★ {format_number(s1.total_stars)}", f"★ {format_number(s2.total_stars)}", s1.total_stars, s2.total_stars)
    render_metric_battle("Followers", format_number(u1.followers), format_number(u2.followers), u1.followers, u2.followers)
    render_metric_battle("Public Repositories", str(s1.total_repos), str(s2.total_repos), s1.total_repos, s2.total_repos)
    render_metric_battle("Total Forks", f"⑂ {format_number(s1.total_forks)}", f"⑂ {format_number(s2.total_forks)}", s1.total_forks, s2.total_forks)
    render_metric_battle("Affiliated Organizations", str(len(m1.orgs)), str(len(m2.orgs)), len(m1.orgs), len(m2.orgs))

    st.markdown("<br/>", unsafe_allow_html=True)

    # ==========================================
    # 6. Comparative Language Distribution
    # ==========================================
    st.subheader("💻 Comparative Language Breakdown")
    
    # Collect top languages from both
    lang_rows = []
    for l in m1.language_breakdown[:6]:
        lang_rows.append({"Language": l.language, "Percentage": l.percentage, "Developer": f"@{u1.login}"})
    for l in m2.language_breakdown[:6]:
        lang_rows.append({"Language": l.language, "Percentage": l.percentage, "Developer": f"@{u2.login}"})

    if lang_rows:
        df_lang = pd.DataFrame(lang_rows)
        
        # Grouped horizontal bar chart
        chart = alt.Chart(df_lang).mark_bar(cornerRadiusTopLeft=4, cornerRadiusTopRight=4).encode(
            x=alt.X('Percentage:Q', title='Percentage of Repositories (%)'),
            y=alt.Y('Language:N', sort='-x', title=None),
            color=alt.Color('Developer:N', scale=alt.Scale(domain=[f"@{u1.login}", f"@{u2.login}"], range=['#58a6ff', '#f778ba'])),
            yOffset='Developer:N',
            tooltip=['Developer', 'Language', alt.Tooltip('Percentage:Q', format='.1f')]
        ).properties(height=260).configure_view(strokeWidth=0).configure_axis(
            labelColor="#8b949e", titleColor="#c9d1d9", gridColor="#21262d"
        ).configure_legend(labelColor="#c9d1d9", titleColor="#58a6ff")

        st.altair_chart(chart, use_container_width=True)
    else:
        st.info("No programming language statistics available for comparison.")

    st.markdown("<br/>", unsafe_allow_html=True)

    # ==========================================
    # 7. Top Starred Repositories Battle
    # ==========================================
    st.subheader("🌟 Top Starred Repositories Showdown")
    col_r1, col_r2 = st.columns(2)
    
    with col_r1:
        st.markdown(f"<h4 style='color:#58a6ff; font-size:1.1rem; margin-bottom:1rem;'>@{u1.login}'s Best Projects</h4>", unsafe_allow_html=True)
        if s1.top_repos:
            for r in s1.top_repos[:3]:
                lang_color = get_language_color(r.language)
                desc = r.description or "No description provided."
                st.markdown(
                    f"""
                    <div class="repo-card" style="margin-bottom:0.8rem;">
                        <div class="repo-title">
                            <a href="{r.html_url or f'https://github.com/{r.full_name}'}" target="_blank" style="color:#58a6ff; text-decoration:none;">📦 {r.name}</a>
                        </div>
                        <div class="repo-desc">{desc[:85] + '...' if len(desc) > 85 else desc}</div>
                        <div class="repo-stats">
                            <span><span class="lang-dot" style="background:{lang_color};"></span> {r.language or 'Unknown'}</span>
                            <span>★ {format_number(r.stargazers_count)}</span>
                            <span>⑂ {format_number(r.forks_count)}</span>
                        </div>
                    </div>
                    """,
                    unsafe_allow_html=True
                )
        else:
            st.info(f"No public repositories found for @{u1.login}.")

    with col_r2:
        st.markdown(f"<h4 style='color:#f778ba; font-size:1.1rem; margin-bottom:1rem;'>@{u2.login}'s Best Projects</h4>", unsafe_allow_html=True)
        if s2.top_repos:
            for r in s2.top_repos[:3]:
                lang_color = get_language_color(r.language)
                desc = r.description or "No description provided."
                st.markdown(
                    f"""
                    <div class="repo-card" style="margin-bottom:0.8rem;">
                        <div class="repo-title">
                            <a href="{r.html_url or f'https://github.com/{r.full_name}'}" target="_blank" style="color:#f778ba; text-decoration:none;">📦 {r.name}</a>
                        </div>
                        <div class="repo-desc">{desc[:85] + '...' if len(desc) > 85 else desc}</div>
                        <div class="repo-stats">
                            <span><span class="lang-dot" style="background:{lang_color};"></span> {r.language or 'Unknown'}</span>
                            <span>★ {format_number(r.stargazers_count)}</span>
                            <span>⑂ {format_number(r.forks_count)}</span>
                        </div>
                    </div>
                    """,
                    unsafe_allow_html=True
                )
        else:
            st.info(f"No public repositories found for @{u2.login}.")

    st.markdown("<br/>", unsafe_allow_html=True)

    # ==========================================
    # 8. AI Architectural Comparison
    # ==========================================
    st.subheader("🤖 AI Architectural Comparison")
    st.markdown(
        """
        <p style="color:#8b949e; font-size:0.95rem;">
            Generate an in-depth AI architectural breakdown synthesizing software engineering paradigms, core technology stacks, and open-source footprints.
        </p>
        """,
        unsafe_allow_html=True
    )

    if st.session_state.compare_ai_analysis:
        st.markdown(
            f"""
            <div class="glass-card" style="padding:1.5rem; border-left:4px solid #a371f7;">
                {st.session_state.compare_ai_analysis}
            </div>
            """,
            unsafe_allow_html=True
        )
        if st.button("🔄 Regenerate AI Comparison"):
            st.session_state.compare_ai_analysis = None
            st.rerun()
    else:
        if st.button("✨ Generate AI Architectural Synthesis", use_container_width=True):
            with st.spinner("🤖 Consulting AI Model to analyze architectural contrast..."):
                stream_gen = stream_ai_comparison(m1, m2)
                full_text = st.write_stream(stream_gen)
                st.session_state.compare_ai_analysis = full_text
            st.rerun()

    st.markdown("<br/>", unsafe_allow_html=True)

    # ==========================================
    # 9. Download Comparative Dossier
    # ==========================================
    report_content = generate_comparison_markdown(m1, m2, st.session_state.compare_ai_analysis)
    st.download_button(
        label="📥 Download Comparative Dossier (.md)",
        data=report_content,
        file_name=f"comparison_{u1.login}_vs_{u2.login}.md",
        mime="text/markdown",
        use_container_width=True
    )
